name: Add mask
on: push
jobs:
    log:
        runs-on: ubuntu-latest
        env:
            PASSWORD: SuperSecretValue
        steps:
            - shell: bash
              run: echo "::add-mask::${PASSWORD}"
            - shell: bash  
              run: echo "${PASSWORD}"
