name: Conditions
on: push
jobs:
        skip-or-run:
            runs-on: ubuntu-latest
            steps:
                - run: echo "Hello, 1"
                - run: echo "Hello, 2"
                  if: ${{contains(github.run_id, '1')}}
