name: Environments
on:
    workflow_dispatch:
        inputs:
            environment-name:
                type: environment
                default: first_test_env
                required: false
                description: Environment name
jobs:
    print:
        runs-on: ubuntu-latest
        environment: ${{inputs.environment-name}}
        env:
            USERNAME: ${{vars.USERNAME}}
            PASSWORD: ${{secrets.PASSWORD}}
        steps:
            - run: echo "${USERNAME}"
            - run: echo "${secret.PASSWORD}"